import { getCollections } from '../mongoDB';

const lowerToOriginal: any = {
    'dusk ce_iii': 'Dusk ce.III',
    'dusk ce_iii crate': 'Dusk ce.III Crate',
    'booker storm rifle model 838': 'Booker Storm Rifle Model 838',
    'booker storm rifle model 838 crate': 'Booker Storm Rifle Model 838 Crate',
    'aalto storm rifle 24': 'Aalto Storm Rifle 24',
    'aalto storm rifle 24 crate': 'Aalto Storm Rifle 24 Crate',
    '7_92mm': '7.92mm',
    '7_92mm crate': '7.92mm Crate',
    'catara mo_ ii': 'Catara mo. II',
    'catara mo_ ii crate': 'Catara mo. II Crate',
    'krn886-127 gast machine gun': 'KRN886-127 Gast Machine Gun',
    'krn886-127 gast machine gun crate': 'KRN886-127 Gast Machine Gun Crate',
    'malone mk_2': 'Malone MK.2',
    'malone mk_2 crate': 'Malone MK.2 Crate',
    '12_7mm': '12.7mm',
    '12_7mm crate': '12.7mm Crate',
    'pt-815 smoke grenade': 'PT-815 Smoke Grenade',
    'pt-815 smoke grenade crate': 'PT-815 Smoke Grenade Crate',
    'ferro 879': 'Ferro 879',
    'ferro 879 crate': 'Ferro 879 Crate',
    'cascadier 873': 'Cascadier 873',
    'cascadier 873 crate': 'Cascadier 873 Crate',
    '8mm': '8mm',
    '8mm crate': '8mm Crate',
    'cometa t2-9': 'Cometa T2-9',
    'cometa t2-9 crate': 'Cometa T2-9 Crate',
    'the hangman 757': 'The Hangman 757',
    'the hangman 757 crate': 'The Hangman 757 Crate',
    '0_44': '0.44',
    '0_44 crate': '0.44 Crate',
    'sampo auto-rifle 77': 'Sampo Auto-Rifle 77',
    'sampo auto-rifle 77 crate': 'Sampo Auto-Rifle 77 Crate',
    'argentir r_ii rifle': 'Argentir r.II Rifle',
    'argentir r_ii rifle crate': 'Argentir r.II Rifle Crate',
    'volta r_i repeater': 'Volta r.I Repeater',
    'volta r_i repeater crate': 'Volta r.I Repeater Crate',
    'fuscina pi_i': 'Fuscina pi.I',
    'fuscina pi_i crate': 'Fuscina pi.I Crate',
    'blakerow 871': 'Blakerow 871',
    'blakerow 871 crate': 'Blakerow 871 Crate',
    'krr2-790 omen': 'KRR2-790 Omen',
    'krr2-790 omen crate': 'KRR2-790 Omen Crate',
    'clancy cinder m3': 'Clancy Cinder M3',
    'clancy cinder m3 crate': 'Clancy Cinder M3 Crate',
    'no_2 loughcaster': 'No.2 Loughcaster',
    'no_2 loughcaster crate': 'No.2 Loughcaster Crate',
    '7_62mm': '7.62mm',
    '7_62mm crate': '7.62mm Crate',
    'brasa shotgun': 'Brasa Shotgun',
    'brasa shotgun crate': 'Brasa Shotgun Crate',
    buckshot: 'Buckshot',
    'buckshot crate': 'Buckshot Crate',
    'the pitch gun mc_v': 'The Pitch Gun mc.V',
    'the pitch gun mc_v crate': 'The Pitch Gun mc.V Crate',
    'lionclaw mc_viii': 'Lionclaw mc.VIII',
    'lionclaw mc_viii crate': 'Lionclaw mc.VIII Crate',
    'no_1 "the liar" submachinegun': 'No.1 "The Liar" Submachinegun',
    'no_1 "the liar" submachinegun crate': 'No.1 "The Liar" Submachinegun Crate',
    'fiddler submachine gun model 868': 'Fiddler Submachine Gun Model 868',
    'fiddler submachine gun model 868 crate': 'Fiddler Submachine Gun Model 868 Crate',
    '9mm smg': '9mm SMG',
    '9mm smg crate': '9mm SMG Crate',
    'krr3-792 auger': 'KRR3-792 Auger',
    'krr3-792 auger crate': 'KRR3-792 Auger Crate',
    'clancy-raca m4': 'Clancy-Raca M4',
    'clancy-raca m4 crate': 'Clancy-Raca M4 Crate',
    '8_5mm': '8.5mm',
    '8_5mm crate': '8.5mm Crate',
    '20 neville anti-tank rifle': '20 Neville Anti-Tank Rifle',
    '20 neville anti-tank rifle crate': '20 Neville Anti-Tank Rifle Crate',
    '20mm': '20mm',
    '20mm crate': '20mm Crate',
    'venom c_ii 35': 'Venom c.II 35',
    'venom c_ii 35 crate': 'Venom c.II 35 Crate',
    'bane 45': 'Bane 45',
    'bane 45 crate': 'Bane 45 Crate',
    'a_t_r_p_g_ shell': 'A.T.R.P.G. Shell',
    'a_t_r_p_g_ shell crate': 'A.T.R.P.G. Shell Crate',
    'bonesaw mk_3': 'Bonesaw MK.3',
    'bonesaw mk_3 crate': 'Bonesaw MK.3 Crate',
    'a_t_r_p_g_ indirect shell': 'A.T.R.P.G. Indirect Shell',
    'a_t_r_p_g_ indirect shell crate': 'A.T.R.P.G. Indirect Shell Crate',
    'cremari mortar': 'Cremari Mortar',
    'cremari mortar crate': 'Cremari Mortar Crate',
    'mortar flare shell': 'Mortar Flare Shell',
    'mortar flare shell crate': 'Mortar Flare Shell Crate',
    'mortar shrapnel shell': 'Mortar Shrapnel Shell',
    'mortar shrapnel shell crate': 'Mortar Shrapnel Shell Crate',
    'mortar shell': 'Mortar Shell',
    'mortar shell crate': 'Mortar Shell Crate',
    'bf5 white ash flask grenade': 'BF5 White Ash Flask Grenade',
    'bf5 white ash flask grenade crate': 'BF5 White Ash Flask Grenade Crate',
    'ignifist 30': 'Ignifist 30',
    'ignifist 30 crate': 'Ignifist 30 Crate',
    'mounted bonesaw mk_3': 'Mounted Bonesaw MK.3',
    'mounted bonesaw mk_3 crate': 'Mounted Bonesaw MK.3 Crate',
    'green ash grenade': 'Green Ash Grenade',
    'green ash grenade crate': 'Green Ash Grenade Crate',
    'bombastone grenade': 'Bombastone Grenade',
    'bombastone grenade crate': 'Bombastone Grenade Crate',
    'a3 harpa fragmentation grenade': 'A3 Harpa Fragmentation Grenade',
    'a3 harpa fragmentation grenade crate': 'A3 Harpa Fragmentation Grenade Crate',
    '150mm': '150mm',
    '150mm crate': '150mm Crate',
    'mammon 91-b': 'Mammon 91-b',
    'mammon 91-b crate': 'Mammon 91-b Crate',
    'daucus isg_iii': 'Daucus isg.III',
    'daucus isg_iii crate': 'Daucus isg.III Crate',
    '120mm': '120mm',
    '120mm crate': '120mm Crate',
    '300mm': '300mm',
    '300mm crate': '300mm Crate',
    '250mm': '250mm',
    '250mm crate': '250mm Crate',
    'anti-tank sticky bomb': 'Anti-Tank Sticky Bomb',
    'anti-tank sticky bomb crate': 'Anti-Tank Sticky Bomb Crate',
    'cutler launcher 4': 'Cutler Launcher 4',
    'cutler launcher 4 crate': 'Cutler Launcher 4 Crate',
    'r_p_g_ shell': 'R.P.G. Shell',
    'r_p_g_ shell crate': 'R.P.G. Shell Crate',
    '68mm at': '68mm AT',
    '68mm at crate': '68mm AT Crate',
    '75mm round': '75mm Round',
    '75mm round crate': '75mm Round Crate',
    '40mm round': '40mm Round',
    '40mm round crate': '40mm Round Crate',
    '30mm': '30mm',
    '30mm crate': '30mm Crate',
    warhead: 'Warhead',
    'warhead crate': 'Warhead Crate',
    binoculars: 'Binoculars',
    'binoculars crate': 'Binoculars Crate',
    "hydra's whisper": "Hydra's Whisper",
    "hydra's whisper crate": "Hydra's Whisper Crate",
    'listening kit': 'Listening Kit',
    'listening kit crate': 'Listening Kit Crate',
    'radio backpack': 'Radio Backpack',
    'radio backpack crate': 'Radio Backpack Crate',
    'alligator charge': 'Alligator Charge',
    'alligator charge crate': 'Alligator Charge Crate',
    shovel: 'Shovel',
    'shovel crate': 'Shovel Crate',
    'sledge hammer': 'Sledge Hammer',
    'sledge hammer crate': 'Sledge Hammer Crate',
    'abisme at-99': 'Abisme AT-99',
    'abisme at-99 crate': 'Abisme AT-99 Crate',
    tripod: 'Tripod',
    'tripod crate': 'Tripod Crate',
    hammer: 'Hammer',
    'hammer crate': 'Hammer Crate',
    wrench: 'Wrench',
    'wrench crate': 'Wrench Crate',
    'buckhorn ccq-18': 'Buckhorn CCQ-18',
    'buckhorn ccq-18 crate': 'Buckhorn CCQ-18 Crate',
    'gas mask': 'Gas Mask',
    'gas mask crate': 'Gas Mask Crate',
    'gas mask filter': 'Gas Mask Filter',
    'gas mask filter crate': 'Gas Mask Filter Crate',
    radio: 'Radio',
    'radio crate': 'Radio Crate',
    'rocket booster': 'Rocket Booster',
    'rocket booster crate': 'Rocket Booster Crate',
    bandages: 'Bandages',
    'bandages crate': 'Bandages Crate',
    'first aid kit': 'First Aid Kit',
    'first aid kit crate': 'First Aid Kit Crate',
    'trauma kit': 'Trauma Kit',
    'trauma kit crate': 'Trauma Kit Crate',
    'blood plasma': 'Blood Plasma',
    'blood plasma crate': 'Blood Plasma Crate',
    'soldier supplies': 'Soldier Supplies',
    'soldier supplies crate': 'Soldier Supplies Crate',
    diesel: 'Diesel',
    'diesel crate': 'Diesel Crate',
    petrol: 'Petrol',
    'petrol crate': 'Petrol Crate',
    'aluminum alloy': 'Aluminum Alloy',
    'aluminum alloy crate': 'Aluminum Alloy Crate',
    'bunker supplies': 'Bunker Supplies',
    'bunker supplies crate': 'Bunker Supplies Crate',
    'basic materials': 'Basic Materials',
    'basic materials crate': 'Basic Materials Crate',
    'explosive materials': 'Explosive Materials',
    'explosive materials crate': 'Explosive Materials Crate',
    'garrison supplies': 'Garrison Supplies',
    'garrison supplies crate': 'Garrison Supplies Crate',
    'heavy explosive materials': 'Heavy Explosive Materials',
    'heavy explosive materials crate': 'Heavy Explosive Materials Crate',
    'iron alloy': 'Iron Alloy',
    'iron alloy crate': 'Iron Alloy Crate',
    'refined materials': 'Refined Materials',
    'refined materials crate': 'Refined Materials Crate',
    salvage: 'Salvage',
    'salvage crate': 'Salvage Crate',
    components: 'Components',
    'components crate': 'Components Crate',
    sulfur: 'Sulfur',
    'sulfur crate': 'Sulfur Crate',
    aluminum: 'Aluminum',
    'aluminum crate': 'Aluminum Crate',
    iron: 'Iron',
    'iron crate': 'Iron Crate',
    wreckage: 'Wreckage',
    'wreckage crate': 'Wreckage Crate',
    'concrete materials': 'Concrete Materials',
    'concrete materials crate': 'Concrete Materials Crate',
    'crude oil': 'Crude Oil',
    'crude oil crate': 'Crude Oil Crate',
    "specialist's overcoat": "Specialist's Overcoat",
    "specialist's overcoat crate": "Specialist's Overcoat Crate",
    'fabri rucksack': 'Fabri Rucksack',
    'fabri rucksack crate': 'Fabri Rucksack Crate',
    'sapper gear': 'Sapper Gear',
    'sapper gear crate': 'Sapper Gear Crate',
    "grenadier's baldric": "Grenadier's Baldric",
    "grenadier's baldric crate": "Grenadier's Baldric Crate",
    'medic fatigues': 'Medic Fatigues',
    'medic fatigues crate': 'Medic Fatigues Crate',
    "physician's jacket": "Physician's Jacket",
    "physician's jacket crate": "Physician's Jacket Crate",
    "legionary's oilcoat": "Legionary's Oilcoat",
    "legionary's oilcoat crate": "Legionary's Oilcoat Crate",
    'recon camo': 'Recon Camo',
    'recon camo crate': 'Recon Camo Crate',
    "outrider's mantle": "Outrider's Mantle",
    "outrider's mantle crate": "Outrider's Mantle Crate",
    'heavy topcoat': 'Heavy Topcoat',
    'heavy topcoat crate': 'Heavy Topcoat Crate',
    'caoivish parka': 'Caoivish Parka',
    'caoivish parka crate': 'Caoivish Parka Crate',
    'legionary fatigues': 'Legionary Fatigues',
    'legionary fatigues crate': 'Legionary Fatigues Crate',
    'infantry battledress': 'Infantry Battledress',
    'infantry battledress crate': 'Infantry Battledress Crate',
    "tankman's coveralls": "Tankman's Coveralls",
    "tankman's coveralls crate": "Tankman's Coveralls Crate",
    'padded boiler suit': 'Padded Boiler Suit',
    'padded boiler suit crate': 'Padded Boiler Suit Crate',
    'r-12 - "salus" ambulance': 'R-12 - "Salus" Ambulance',
    'r-12 - "salus" ambulance crate': 'R-12 - "Salus" Ambulance Crate',
    'dunne responder 3e': 'Dunne Responder 3e',
    'dunne responder 3e crate': 'Dunne Responder 3e Crate',
    't3 "xiphos"': 'T3 "Xiphos"',
    't3 "xiphos" crate': 'T3 "Xiphos" Crate',
    't12 "actaeon" tankette': 'T12 "Actaeon" Tankette',
    't12 "actaeon" tankette crate': 'T12 "Actaeon" Tankette Crate',
    "o'brien v_121 highlander": "O'Brien v.121 Highlander",
    "o'brien v_121 highlander crate": "O'Brien v.121 Highlander Crate",
    't5 "percutio"': 'T5 "Percutio"',
    't5 "percutio" crate': 'T5 "Percutio" Crate',
    "o'brien v_101 freeman": "O'Brien v.101 Freeman",
    "o'brien v_101 freeman crate": "O'Brien v.101 Freeman Crate",
    "o'brien v_110": "O'Brien v.110",
    "o'brien v_110 crate": "O'Brien v.110 Crate",
    'bms - aquatipper': 'BMS - Aquatipper',
    'bms - aquatipper crate': 'BMS - Aquatipper Crate',
    'blumfield lk205': 'Blumfield LK205',
    'blumfield lk205 crate': 'Blumfield LK205 Crate',
    'r-15 - "chariot"': 'R-15 - "Chariot"',
    'r-15 - "chariot" crate': 'R-15 - "Chariot" Crate',
    'dunne caravaner 2f': 'Dunne Caravaner 2f',
    'dunne caravaner 2f crate': 'Dunne Caravaner 2f Crate',
    'bms - universal assembly rig': 'BMS - Universal Assembly Rig',
    'bms - universal assembly rig crate': 'BMS - Universal Assembly Rig Crate',
    'bms - class 2 mobile auto-crane': 'BMS - Class 2 Mobile Auto-Crane',
    'bms - class 2 mobile auto-crane crate': 'BMS - Class 2 Mobile Auto-Crane Crate',
    'noble widow mk_ xiv': 'Noble Widow MK. XIV',
    'noble widow mk_ xiv crate': 'Noble Widow MK. XIV Crate',
    'aa-2 battering ram': 'AA-2 Battering Ram',
    'aa-2 battering ram crate': 'AA-2 Battering Ram Crate',
    '68-45 "smelter" heavy field gun': '68-45 "Smelter" Heavy Field Gun',
    '68-45 "smelter" heavy field gun crate': '68-45 "Smelter" Heavy Field Gun Crate',
    'collins cannon 68mm': 'Collins Cannon 68mm',
    'collins cannon 68mm crate': 'Collins Cannon 68mm Crate',
    'balfour rampart 40mm': 'Balfour Rampart 40mm',
    'balfour rampart 40mm crate': 'Balfour Rampart 40mm Crate',
    'balfour wolfhound 40mm': 'Balfour Wolfhound 40mm',
    'balfour wolfhound 40mm crate': 'Balfour Wolfhound 40mm Crate',
    '120-68 "koronides" field gun': '120-68 "Koronides" Field Gun',
    '120-68 "koronides" field gun crate': '120-68 "Koronides" Field Gun Crate',
    'g40 "sagittarii"': 'G40 "Sagittarii"',
    'g40 "sagittarii" crate': 'G40 "Sagittarii" Crate',
    'swallowtail 988/127-2': 'Swallowtail 988/127-2',
    'swallowtail 988/127-2 crate': 'Swallowtail 988/127-2 Crate',
    'balfour falconer 250mm': 'Balfour Falconer 250mm',
    'balfour falconer 250mm crate': 'Balfour Falconer 250mm Crate',
    'bms - packmule flatbed': 'BMS - Packmule Flatbed',
    'bms - packmule flatbed crate': 'BMS - Packmule Flatbed Crate',
    'bms - ironship': 'BMS - Ironship',
    'bms - ironship crate': 'BMS - Ironship Crate',
    'type c - "charon"': 'Type C - "Charon"',
    'type c - "charon" crate': 'Type C - "Charon" Crate',
    '74c-2 ronan meteora gunship': '74c-2 Ronan Meteora Gunship',
    '74c-2 ronan meteora gunship crate': '74c-2 Ronan Meteora Gunship Crate',
    '74b-1 ronan gunship': '74b-1 Ronan Gunship',
    '74b-1 ronan gunship crate': '74b-1 Ronan Gunship Crate',
    'hh-d "peltast"': 'HH-d "Peltast"',
    'hh-d "peltast" crate': 'HH-d "Peltast" Crate',
    'hh-a "javelin"': 'HH-a "Javelin"',
    'hh-a "javelin" crate': 'HH-a "Javelin" Crate',
    'hh-b "hoplite"': 'HH-b "Hoplite"',
    'hh-b "hoplite" crate': 'HH-b "Hoplite" Crate',
    'niska mk_ ii blinder': 'Niska Mk. II Blinder',
    'niska mk_ ii blinder crate': 'Niska Mk. II Blinder Crate',
    'niska mk_ i gun motor carriage': 'Niska Mk. I Gun Motor Carriage',
    'niska mk_ i gun motor carriage crate': 'Niska Mk. I Gun Motor Carriage Crate',
    'bms - scrap hauler': 'BMS - Scrap Hauler',
    'bms - scrap hauler crate': 'BMS - Scrap Hauler Crate',
    'ab-8 "acheron"': 'AB-8 "Acheron"',
    'ab-8 "acheron" crate': 'AB-8 "Acheron" Crate',
    'ab-11 "doru"': 'AB-11 "Doru"',
    'ab-11 "doru" crate': 'AB-11 "Doru" Crate',
    'mulloy apc': 'Mulloy APC',
    'mulloy apc crate': 'Mulloy APC Crate',
    'hc-2 "scorpion"': 'HC-2 "Scorpion"',
    'hc-2 "scorpion" crate': 'HC-2 "Scorpion" Crate',
    'devitt-caine mk_ iv mmr': 'Devitt-Caine Mk. IV MMR',
    'devitt-caine mk_ iv mmr crate': 'Devitt-Caine Mk. IV MMR Crate',
    'h5 "hatchet"': 'H5 "Hatchet"',
    'h5 "hatchet" crate': 'H5 "Hatchet" Crate',
    'devitt ironhide mk_ iv': 'Devitt Ironhide Mk. IV',
    'devitt ironhide mk_ iv crate': 'Devitt Ironhide Mk. IV Crate',
    'h-8 "kraneska"': 'H-8 "Kraneska"',
    'h-8 "kraneska" crate': 'H-8 "Kraneska" Crate',
    'h-10 "pelekys"': 'H-10 "Pelekys"',
    'h-10 "pelekys" crate': 'H-10 "Pelekys" Crate',
    'devitt mk_ iii': 'Devitt Mk. III',
    'devitt mk_ iii crate': 'Devitt Mk. III Crate',
    '86k-a "bardiche"': '86K-a "Bardiche"',
    '86k-a "bardiche" crate': '86K-a "Bardiche" Crate',
    'gallagher outlaw mk_ ii': 'Gallagher Outlaw Mk. II',
    'gallagher outlaw mk_ ii crate': 'Gallagher Outlaw Mk. II Crate',
    '85k-b "falchion"': '85K-b "Falchion"',
    '85k-b "falchion" crate': '85K-b "Falchion" Crate',
    '85k-a "spatha"': '85K-a "Spatha"',
    '85k-a "spatha" crate': '85K-a "Spatha" Crate',
    'silverhand chieftain - mk_ vi': 'Silverhand Chieftain - Mk. VI',
    'silverhand chieftain - mk_ vi crate': 'Silverhand Chieftain - Mk. VI Crate',
    'silverhand - mk_ iv': 'Silverhand - Mk. IV',
    'silverhand - mk_ iv crate': 'Silverhand - Mk. IV Crate',
    'hc-7 "ballista"': 'HC-7 "Ballista"',
    'hc-7 "ballista" crate': 'HC-7 "Ballista" Crate',
    '03mm "caster"': '03MM "Caster"',
    '03mm "caster" crate': '03MM "Caster" Crate',
    '00ms "stinger"': '00MS "Stinger"',
    '00ms "stinger" crate': '00MS "Stinger" Crate',
    'kivela power wheel 80-1': 'Kivela Power Wheel 80-1',
    'kivela power wheel 80-1 crate': 'Kivela Power Wheel 80-1 Crate',
    'rr-3 "stolon" tanker_': 'RR-3 "Stolon" Tanker.',
    'rr-3 "stolon" tanker_ crate': 'RR-3 "Stolon" Tanker. Crate',
    'dunne fuelrunner 2d': 'Dunne Fuelrunner 2d',
    'dunne fuelrunner 2d crate': 'Dunne Fuelrunner 2d Crate',
    'king gallant mk_ ii': 'King Gallant Mk. II',
    'king gallant mk_ ii crate': 'King Gallant Mk. II Crate',
    'king spire mk_ i': 'King Spire Mk. I',
    'king spire mk_ i crate': 'King Spire Mk. I Crate',
    'uv-05a "argonaut"': 'UV-05a "Argonaut"',
    'uv-05a "argonaut" crate': 'UV-05a "Argonaut" Crate',
    'uv-24 "icarus"': 'UV-24 "Icarus"',
    'uv-24 "icarus" crate': 'UV-24 "Icarus" Crate',
    'drummond spitfire 100d': 'Drummond Spitfire 100d',
    'drummond spitfire 100d crate': 'Drummond Spitfire 100d Crate',
    'uv-5c "odyssey"': 'UV-5c "Odyssey"',
    'uv-5c "odyssey" crate': 'UV-5c "Odyssey" Crate',
    'drummond loscann 55c': 'Drummond Loscann 55c',
    'drummond loscann 55c crate': 'Drummond Loscann 55c Crate',
    'drummond 100a': 'Drummond 100a',
    'drummond 100a crate': 'Drummond 100a Crate',
    't20 "ixion" tankette': 'T20 "Ixion" Tankette',
    't20 "ixion" tankette crate': 'T20 "Ixion" Tankette Crate',
    'bms - white whale': 'BMS - White Whale',
    'bms - white whale crate': 'BMS - White Whale Crate',
    'r-1 hauler': 'R-1 Hauler',
    'r-1 hauler crate': 'R-1 Hauler Crate',
    'dunne leatherback 2a': 'Dunne Leatherback 2a',
    'dunne leatherback 2a crate': 'Dunne Leatherback 2a Crate',
    'r-5 "atlas" hauler': 'R-5 "Atlas" Hauler',
    'r-5 "atlas" hauler crate': 'R-5 "Atlas" Hauler Crate',
    'dunne loadlugger 3c': 'Dunne Loadlugger 3c',
    'dunne loadlugger 3c crate': 'Dunne Loadlugger 3c Crate',
    'r-5b "sisyphus" hauler': 'R-5b "Sisyphus" Hauler',
    'r-5b "sisyphus" hauler crate': 'R-5b "Sisyphus" Hauler Crate',
    'dunne landrunner 12c': 'Dunne Landrunner 12c',
    'dunne landrunner 12c crate': 'Dunne Landrunner 12c Crate',
    'r-9 "speartip" escort"': 'R-9 "Speartip" Escort"',
    'r-9 "speartip" escort" crate': 'R-9 "Speartip" Escort" Crate',
    'dunne transport': 'Dunne Transport',
    'dunne transport crate': 'Dunne Transport Crate',
    'barbed wire pallet': 'Barbed Wire Pallet',
    'barbed wire pallet crate': 'Barbed Wire Pallet Crate',
    'concrete mixer': 'Concrete Mixer',
    'concrete mixer crate': 'Concrete Mixer Crate',
    '68mm anti-tank cannon': '68mm Anti-Tank Cannon',
    '68mm anti-tank cannon crate': '68mm Anti-Tank Cannon Crate',
    '50-500 "thunderbolt" cannon': '50-500 "Thunderbolt" Cannon',
    '50-500 "thunderbolt" cannon crate': '50-500 "Thunderbolt" Cannon Crate',
    'huber exalt 150mm': 'Huber Exalt 150mm',
    'huber exalt 150mm crate': 'Huber Exalt 150mm Crate',
    'huber lariat 120mm': 'Huber Lariat 120mm',
    'huber lariat 120mm crate': 'Huber Lariat 120mm Crate',
    '12_7 anti infantry flak gun': '12.7 Anti Infantry Flak Gun',
    '12_7 anti infantry flak gun crate': '12.7 Anti Infantry Flak Gun Crate',
    'metal beam pallet': 'Metal Beam Pallet',
    'metal beam pallet crate': 'Metal Beam Pallet Crate',
    'resource container': 'Resource Container',
    'resource container crate': 'Resource Container Crate',
    'sandbag pallet': 'Sandbag Pallet',
    'sandbag pallet crate': 'Sandbag Pallet Crate',
    'shipping container': 'Shipping Container',
    'shipping container crate': 'Shipping Container Crate',
    'small shipping container': 'Small Shipping Container',
    'small shipping container crate': 'Small Shipping Container Crate',
    'barbed wire': 'Barbed Wire',
    'barbed wire crate': 'Barbed Wire Crate',
    sandbags: 'Sandbags',
    'sandbags crate': 'Sandbags Crate',
    'metal beam': 'Metal Beam',
    'metal beam crate': 'Metal Beam Crate',
    'lamentum mm_iv': 'Lamentum mm.IV',
    'lamentum mm_iv crate': 'Lamentum mm.IV Crate',
    '"typhon" ra_xii': '"Typhon" ra.XII',
    '"typhon" ra_xii crate': '"Typhon" ra.XII Crate',
    'culter foebreaker': 'Culter Foebreaker',
    'culter foebreaker crate': 'Culter Foebreaker Crate',
    'ahti model 2': 'Ahti Model 2',
    'ahti model 2 crate': 'Ahti Model 2 Crate',
    'malone ratcatcher mk_ 1': 'Malone Ratcatcher Mk. 1',
    'malone ratcatcher mk_ 1 crate': 'Malone Ratcatcher Mk. 1 Crate',
    copper: 'Copper',
    'copper crate': 'Copper Crate',
    'copper alloy': 'Copper Alloy',
    'copper alloy crate': 'Copper Alloy Crate'
}

const generateMsg = async (updateMsg: boolean): Promise<Array<any>> => {
    const collections = getCollections()
    let stockpileHeader = "**__Stockpiler Discord Bot Report__** \n_All quantities in **crates**_"
    let stockpileMsgsHeader = "**__Stockpiles__** \n\n ----------"
    let stockpileMsgs = NodeCacheObj.get("stockpileHeader") as Array<string>
    let targetMsg = NodeCacheObj.get("targetMsg") as string
    let stockpileNames: String[] = []

    if (updateMsg || !stockpileMsgs || !targetMsg) {
        const targets = await collections.targets.findOne({})
        const stockpilesList = await collections.stockpiles.find({}).toArray()
        const configObj = (await collections.config.findOne({}))!

        let stockpiles: Array<any> = []
        if ("orderSettings" in configObj) {
            for (let i = 0; i < configObj.orderSettings.length; i++) {
                for (let x = 0; x < stockpilesList.length; x++) {
                    if (stockpilesList[x].name === configObj.orderSettings[i]) {
                        stockpiles.push(stockpilesList[x])
                        break
                    }
                }
            }
        }
        else stockpiles = stockpilesList

        stockpileMsgs = []
        const totals: any = {}


        for (let i = 0; i < stockpiles.length; i++) {
            const current = stockpiles[i]
            let currentStockpileMsg = ""
            currentStockpileMsg += `**${current.name}** (as of <t:${Math.floor(current.lastUpdated.getTime() / 1000)}>) ${"timeLeft" in current ? `[Time Left: <t:${Math.floor(current.timeLeft.getTime() / 1000)}:R>]` : ""}\n`
            for (const item in current.items) {

                currentStockpileMsg += "`" + lowerToOriginal[item] + "` - " + current.items[item] + "\n"

                if (item in totals) totals[item] += current.items[item]
                else totals[item] = current.items[item]

            }
            currentStockpileMsg += "----------"
            while (currentStockpileMsg.length > 2000) {

                const sliced = currentStockpileMsg.slice(0, 2000)
                const lastEnd = sliced.lastIndexOf("\n")
                const finalMsg = sliced.slice(0, lastEnd)

                stockpileMsgs.push(finalMsg)
                currentStockpileMsg = currentStockpileMsg.slice(lastEnd, currentStockpileMsg.length)
            }
            stockpileMsgs.push(currentStockpileMsg)

            stockpileNames.push(current.name)
        }

        targetMsg = "**__Targets__** \n\n"
        if (targets) {
            for (const target in targets) {
                if (target !== "_id") {
                    targetMsg += `\`${lowerToOriginal[target]}\` - ${target in totals ? totals[target] : "0"}/${targets[target].min} ${totals[target] >= targets[target].min ? "✅" : "❌"} (Max: ${targets[target].max}) ${"prodLocation" in targets[target] ? "[" + targets[target].prodLocation + "]" : ""}\n`
                }
            }
        }
        targetMsg += "\n"

        NodeCacheObj.set("stockpileMsgs", stockpileMsgs)
        NodeCacheObj.set("targetMsg", targetMsg)
    }

    return [stockpileHeader, stockpileMsgs, targetMsg, stockpileMsgsHeader, stockpileNames]
}


export default generateMsg
